### ISSUE TITLE
Font Update: Tiny5

### ISSUE THREAD

**Issue by Gissio** [fontsource/font-files#94]
### Font Name

Tiny5

### Link to font source

https://github.com/Gissio/font_tiny5

### Link to font license

https://openfontlicense.org/

### Additional context

Hello there,

I've just published the 2.0.0 update of the Tiny5 font (Ihttps://github.com/Gissio/font_tiny5). Among the new features are:

* Variable font support with three axes: pixel volume, roundness and bleed.
* Support for vietnamese and more african languages.
* A new presentation and samples.

It would be great if you could update your website (https://fontsource.org/fonts/tiny5). Perhaps it could make it as a new font, as the differences are quite significant.

Best regards,
and wishing you a happy new year,

Stefan Schmidt.

**Comment by ayuhito** [comment]
Hi there! Since `Tiny5` is a font that we mirror from Google Fonts, I think it is better we let Google handle this and we will automatically mirror it in the future. Since our system only supports variable fonts from Google Fonts and not via custom submission, most of the changes wouldn't really come through otherwise.

Ref: https://github.com/google/fonts/issues/8779

**Comment by Gissio** [comment]
Thanks for the quick reply!

I wasn't aware fontsource mirrors automatically mirror, so what you propose makes a lot of sense!

Happy new year!
